In [1]:
 # Julia

In [2]:
# 数组

In [3]:
# 创建一个数组

In [4]:
# 使用[]
arr = [1, 2,3, 4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [12]:
# 使用Array构造函数
# 声明一个长度为5，未初始化的一维整数数组
# 这个方法产生的数组值都是随机的，只是起到占位的作用
# 这个方法不是很常用
arr1 = Array{Int, 1}(undef, 5)

5-element Vector{Int64}:
 0
 1
 1
 0
 0

In [13]:
# 使用ones函数生成一个全是1的数组
arr2 = ones(10)

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [17]:
# 使用zeros函数生成一个全是0的数组
zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [24]:
# 使用collect函数生成一个范围数组
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [25]:
# 使用range和collect函数联合生成一个数组
collect(range(1, stop=10, length=5))

5-element Vector{Float64}:
  1.0
  3.25
  5.5
  7.75
 10.0

In [26]:
# 数组的查询

In [27]:
test_arr = collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [28]:
# 使用索引直接访问元素
test_arr[3] # 访问第三个元素

3

In [29]:
# 使用切片访问一定范围内的元素
test_arr[1:3]

3-element Vector{Int64}:
 1
 2
 3

In [31]:
# 使用多个索引访问一个数组
test_arr[[1,2,3]]

3-element Vector{Int64}:
 1
 2
 3

In [33]:
# 查询数组长度
length(test_arr)

5

In [35]:
# 数组的条件查询，我感觉非常重要
# 查询所有大于等于2的元素
test_arr[test_arr .>= 2]

4-element Vector{Int64}:
 2
 3
 4
 5

In [ ]:
# findall 查询返回条件元素的索引
findall(x -> x > 2, test_arr)
# 更复杂的情况
findall(x -> x > 3 && x % 2 ==0, test_arr)


1-element Vector{Int64}:
 4

In [40]:
# 或者直接再findall中使用函数
function my_filter(x)
    return x > 2 && x %2 ==0
end
findall(my_filter, test_arr )

1-element Vector{Int64}:
 4

In [41]:
# 创建一个由十个随机整数（1-100） 组成的数组
arr = rand(1:100, 10)

10-element Vector{Int64}:
 11
 94
 25
 27
 14
 79
 60
 94
 57
 52

In [ ]:
# 找出数组中所有的偶数
arr[findall(my_filter, arr)]

5-element Vector{Int64}:
 94
 14
 60
 94
 52

In [15]:
arr = [
    "Alison",
    "Bee",
    "Cate",
    "Dex",
    "Elise",
    "Fisher",
    "Gray",
    "Harden",
    "Ignore"
]

# 使用匿名函数检查长度为 3 的元素
result1 = arr[findall(x -> length(x) == 3, arr)]

2-element Vector{String}:
 "Bee"
 "Dex"

In [32]:
# Julia 中正则表达式的使用
# 在 findall 中使用正则表达式
# 查找名字长度为3
arr[findall(x -> occursin(r"^.{3}$", x), arr)]

2-element Vector{String}:
 "Bee"
 "Dex"

In [38]:
# 往数组中添加元素
# 使用原地函数往数组末尾添加一个函数
arr = rand(1:100, 10)
push!(arr, 36)

11-element Vector{Int64}:
 19
 76
 33
  1
 39
 86
 87
 24
 16
  9
 36

In [39]:
# 往一个数组的末尾添加一个数组
append!(arr, [21,22,23])

14-element Vector{Int64}:
 19
 76
 33
  1
 39
 86
 87
 24
 16
  9
 36
 21
 22
 23

In [42]:
# 往数组中间插入一个元素
insert!(arr, 3, 100)

15-element Vector{Int64}:
  19
  76
 100
  33
   1
  39
  86
  87
  24
  16
   9
  36
  21
  22
  23

In [65]:
# 数组删除一个元素

pop!(arr1)


4

In [66]:
# 删除数组最后的一个元素

In [67]:
arr

13-element Vector{Int64}:
  19
  76
 100
  33
   1
  39
  86
  87
  24
  16
   9
  36
  21

In [68]:
pop!(arr)

21

In [69]:
arr

12-element Vector{Int64}:
  19
  76
 100
  33
   1
  39
  86
  87
  24
  16
   9
  36

In [80]:
# 元组
tupl = (1,2,3,4,5)

(1, 2, 3, 4, 5)

In [88]:
# 创建一个元组
# 使用逗号创建
tup1 = 1,2,3
println(tup1)
# 使用括号创建
tup2 = (1, 2,3)
println(tup2)
# 直接使用tuple函数
println(tuple(1,2,3))
# 将数组转换为元组
println(tuple([1,2,3]...))
# 使用collect函数
println(tuple(collect(1:10)...))

(1, 2, 3)
(1, 2, 3)
(1, 2, 3)
(1, 2, 3)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [91]:
# 使用索引查询元组中的元素
tup1[1]

1

In [92]:
# 遍历一个元组
for ele in tup1
    println(ele)
end

1
2
3


In [93]:
# 遍历一个数组
for i in arr1
    println(i)
end

1
2


In [99]:
# 从元组中筛选元素
tup = tuple(1:10...)
filter(x -> x>=5, tup)

(5, 6, 7, 8, 9, 10)

In [107]:
# 改变数组中的每一个元素
# 广播
arr = collect(1:10)
println(arr)
print(arr.*2)
# 使用map函数
println(map(x -> x * 3, arr))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20][3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


ArgumentError: ArgumentError: map! requires at least one "source" argument

In [113]:
arr = [1, 5, 7, 10, 15]

# 创建一个新的数组来存储 map! 的结果
result = similar(arr)

# 使用链式调用
final_result = arr |>
    x -> map!(y -> y * 2, result, x) |>
    x -> filter!(y -> y > 10, x)

println(final_result)  # 输出: [14, 20, 30]


[14, 20, 30]


In [111]:
arr

5-element Vector{Int64}:
  1
  5
  7
 10
 15

In [115]:
# 数组推导式
arr1 = [i* 2 for i in arr]

5-element Vector{Int64}:
  2
 10
 14
 20
 30

In [116]:
people = [
    (name = "Alice", age = 30, city = "New York"),
    (name = "Bob", age = 25, city = "San Francisco"),
    (name = "Charlie", age = 35, city = "Los Angeles")
]


3-element Vector{@NamedTuple{name::String, age::Int64, city::String}}:
 (name = "Alice", age = 30, city = "New York")
 (name = "Bob", age = 25, city = "San Francisco")
 (name = "Charlie", age = 35, city = "Los Angeles")

In [117]:
using   DataFrames

In [118]:
DataFrame(people)

3×3 DataFrame
 Row │ name     age    city          
     │ String   Int64  String        
─────┼───────────────────────────────
   1 │ Alice       30  New York
   2 │ Bob         25  San Francisco
   3 │ Charlie     35  Los Angeles

In [120]:
# named tuple
tup = (
    name = "Bee",
    age = 30,
    height = 173.5,
    weight = 74.2
)

(name = "Bee", age = 30, height = 173.5, weight = 74.2)

In [121]:
# 具名元组的查询
tup.name

"Bee"

In [123]:
tup.age

30

In [126]:
df =DataFrame([tup])

1×4 DataFrame
 Row │ name    age    height   weight  
     │ String  Int64  Float64  Float64 
─────┼─────────────────────────────────
   1 │ Bee        30    173.5     74.2

In [127]:
# 便利具名元组
for i in tup
    println(i)
end

Bee
30
173.5
74.2


In [128]:
# 遍历具名元组的键
for key in keys(tup)
    println(key)
end

name
age
height
weight


In [132]:
# 创建一个字典
my_dic = Dict(
    "name"=>"Bee",
    "age"=>30,
    "height"=>173.5
)

Dict{String, Any} with 3 entries:
  "name"   => "Bee"
  "height" => 173.5
  "age"    => 30

In [133]:
my_dic["name"]

"Bee"

In [134]:
# 遍历一个字典
for (k, v) in my_dic
    println("Key: $k, Value: $v")
end

Key: name, Value: Bee
Key: height, Value: 173.5
Key: age, Value: 30


In [138]:
using DataFrames
df[!,:name == "Bee"]


MethodError: MethodError: no method matching getindex(::DataFrame, ::typeof(!), ::Bool)

Closest candidates are:
  getindex(::DataFrame, ::typeof(!), !Matched::Union{Colon, Regex, All, Between, Cols, InvertedIndex, AbstractVector})
   @ DataFrames ~/.julia/packages/DataFrames/kcA9R/src/dataframe/dataframe.jl:631
  getindex(::DataFrame, ::typeof(!), !Matched::Union{Signed, Unsigned})
   @ DataFrames ~/.julia/packages/DataFrames/kcA9R/src/dataframe/dataframe.jl:548
  getindex(::DataFrame, ::typeof(!), !Matched::Union{AbstractString, Symbol})
   @ DataFrames ~/.julia/packages/DataFrames/kcA9R/src/dataframe/dataframe.jl:556
  ...
